name: Docker Build and Push
# Build & Push builds the simapp docker image on every push to master
# and pushes the image to a private Google Artifact Registry.
on:
  push:
    branches:
      - main
    tags:
      - '**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

# Set concurrency for this workflow to cancel in-progress jobs if retriggered.
# The github.ref is only available when triggered by a PR so fall back to github.run_id for other cases.
# The github.run_id is unique for each run, giving each such invocation it's own unique concurrency group.
# Basically, if you push to a PR branch, jobs that are still running for that PR will be cancelled.
# But jobs started because of a merge to main or a release tag push are not cancelled.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  heighliner-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/setup-qemu-action@v3

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: us-central1-docker.pkg.dev/provlabs-test/docker/provenance
          flavor: |
            prefix=heighliner-,onlatest=true
          tags: |
            type=edge
            type=ref,event=pr
            type=ref,event=tag

      - uses: google-github-actions/auth@v1
        id: auth
        with:
          token_format: access_token
          workload_identity_provider: projects/815721530660/locations/global/workloadIdentityPools/gha-runner-pool/providers/gha-runner-pool-provider
          service_account: gha-runner@provlabs-test.iam.gserviceaccount.com

      - uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      # lock to "linux/amd64" only for now since cross compilation is throwing errors
      - uses: strangelove-ventures/heighliner-build-action@main
        with:
          heighliner-tag: v1.7.0
          chain: provenance
          local: true
          tag: ${{ steps.meta.outputs.version }}
          registry: us-central1-docker.pkg.dev
          platform: linux/amd64
          dockerfile: cosmos
          build-target: |
            make install
          binaries: |
            - /go/bin/provenanced
          build-env: |
            - "WITH_LEDGER=false"
            - "BUILD_TAGS=muslc musl dynamic"
          skip: ${{ github.event_name == 'pull_request' }}

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - run: go mod vendor

      - uses: docker/setup-buildx-action@v3

      - uses: docker/setup-qemu-action@v3

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: us-central1-docker.pkg.dev/provlabs-test/docker/provenance
          tags: |
            type=edge
            type=ref,event=pr
            type=ref,event=tag

      - uses: google-github-actions/auth@v1
        id: auth
        with:
          token_format: access_token
          workload_identity_provider: projects/815721530660/locations/global/workloadIdentityPools/gha-runner-pool/providers/gha-runner-pool-provider
          service_account: gha-runner@provlabs-test.iam.gserviceaccount.com

      - uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          target: run
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}
          platforms: linux/amd64,linux/arm64
          file: docker/blockchain/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
